Added Unreal information to MR performance article
MicrosoftDocs/mixed-reality pull request #162
Opened 2021-01-08 11:56 UTC by luis-valverde-ms

Just mirrored what we already do for Unity.

2021-01-08 11:57 UTC, PRMerger20 commented
@luis-valverde-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change. @hferrone

2021-01-08 12:04 UTC, luis-valverde-ms commented
@sajidfarooq , I just added links to a few UE docs but there is more info in the article that is specific to Unity for which we don't have a UE equivalent. Would you mind giving the document a pass and add anything else you think is worth adding? We can do it via this PR or separately, whatever suits.

2021-01-08 18:57 UTC, hferrone commented
Hi @luis-valverde-ms - all internal PRs need to go through the private repo in the future. Thanks for your contribution!

2021-01-19 18:27 UTC, sajidfarooq commented on mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/understanding-performance-for-mixed-reality.md
I would add "Pix" here as well. It is especially useful for HL2 debugging

2021-01-19 18:31 UTC, sajidfarooq commented on mixed-reality-docs/mr-dev-docs/develop/platform-capabilities-and-apis/understanding-performance-for-mixed-reality.md
Performance guidelines for Artists and Designers: https://docs.unrealengine.com/en-US/TestingAndOptimization/PerformanceAndProfiling/Guidelines/index.html

Though for VR, still very useful info: https://docs.unrealengine.com/en-US/SharingAndReleasing/XRDevelopment/VR/DevelopVR/ContentSetup/index.html

2021-01-19 18:31 UTC, sajidfarooq requested changes
Added some more useful links

2021-01-20 10:57 UTC, PRMerger20 commented
@luis-valverde-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change. @hferrone

2021-01-20 16:26 UTC, merged

2021-01-20 16:26 UTC, PRMerger13 commented
@hferrone : Thanks for your contribution! The author(s) have been notified to review your proposed change. @hferrone